### ISSUE TITLE
Source encoding and whitespaces

### ISSUE THREAD

**Issue by ak-at-aries** [polarfire-soc/hart-software-services#15]
Several source files under ./baremetal/ are using UTF-8 encoding (over ASCII) with no real technical justification,
the problem files may be listed with the following command:

`find . -type f -name \*.[ch] | xargs file | grep UTF`

Apparently, non-ASCII characters are used for an apostrophe, a bullet in lists, may be something else.

Some source files have blanks at the end of line and empty lines at the end (e.g. ./services/mmc/mmc_api.c)

**Comment by griffini** [comment]
This should be resolved as of commits aad7a6952c9cc9fb05c13547f22260fa3c33171c and 72d8277cd410f0165a490dbc97d32bcdaa7d6d75
