### ISSUE TITLE
I2C doesn't work at all

### ISSUE THREAD

**Issue by eenurkka** [polarfire-soc/hart-software-services#23]
I have the Polarfire ES kit. I2C driver exists in the HSS, but it looks like it's unused. I use the I2C in my own code, but I cannot get it to work. Any register write into i2c registers starting from I2C_A_LO / I2C_B_LO (0x2010A000 / 0x2010B000) as well as I2C_B_LO / I2C_B_HI is lost, meaning a readback shows it's all zeroes although I write the enable bit, slave address etc.  According to MSS configurator and the HSS .xml file, I2C1 should be enabled in the board.

Also I make sure these bits are properly configured:
1. SOFT_RESET_CR: clear i2c1 bit
2. Make sure SUBBLK_CLOCK_CR i2c1 bit is set
3. IOMUX0_CR i2c1 fabric is set

Am I missing something regarding the I2C?

**Comment by hughbreslin** [comment]
Hey @eenurkka have you tried the PAC1934 bare metal example project? https://github.com/polarfire-soc/polarfire-soc-bare-metal-library/tree/master/examples/mss-i2c/mpfs-i2c-pac1934-sensor

It uses I2C1 to get some data from the PAC1934 on the kit so its a good starting point to seeing a working I2C implementation for what you're trying to do. Its not clear from your description what the cause of the issue is - are you getting a lockup and nothing happens or do you get a timeout?

**Comment by eenurkka** [comment]
Thanks @hughbreslin for the fast response and pointing out the bare metal project. I will look into it. My problem is that anything I write to the I2C registers, is lost. For example, I write slave address  0x10 to the slave address register (I2C0_SLAVE0ADR), and read it back, it's just only zeroes, although I'd expect to read 0x10 back from it.

**Comment by griffini** [comment]
Hi @eenurkka, are you trying to access the I2C after having booting from the HSS?

If so, then unless you have enabled the I2C0 peripheral, it is probably still in reset.  The HSS doesn't use I2C currently.  When you mention the HSS source includes the I2C driver, what you are actually referring to is the mpfs_hal, which the HSS uses as a library.

You need to clear bit 12  of the SOFT_RESET_CR and set bit 12 of SUBBLK_CLOCK_CR to take I2C0 out of reset and enable its clock.  If you look at HSS_Setup_Clocks() in init/hss_sys_setup.c you'll see the routine you'll need to modify to enable I2C0.

**Comment by hughbreslin** [comment]
One question:

`IOMUX0_CR i2c1 fabric is set` 

Have you also updated the design to route these pins somewhere? For the PAC we route to MSS I/Os not the fabric so I'm wondering why you've done this 🙂

**Comment by eenurkka** [comment]
@hughbreslin , I use the defaults. The bit 3 at IOMUX0_CR is set (i2c1_fabric), which I interpreted as "routed to fabric". MSS configurator says "MSS I/Os Bank2B".

**Comment by eenurkka** [comment]
I think I found out what's wrong: for some reason, SOFT_RESET_CR needs to be cleared from HSS. My setup is such that I run HSS like in the example, but I have only hart1 running an OS (all other harts not running any). I can clear the bit from hart1 as well, but the i2c doesn't come functional. Hart1 runs in machine privileges.  Now that I clear the bits from HSS:

+    SYSREG->SOFT_RESET_CR &=
+        ~(uint32_t)(SOFT_RESET_CR_I2C0_MASK | SOFT_RESET_CR_I2C1_MASK);

Then, for some reason, it looks like i2c works.

**Comment by griffini** [comment]
The HSS puts everything (except eNVM) into reset, and takes certain peripherals back out of reset. Currently it does not take the I2C out of reset. By clearing the bits, you are taking these peripherals out of reset in your own code. I would expect you to need to do this - however, it should be possible for you to do this on U54_1.

Are you seeing that if you execute

```
SYSREG->SOFT_RESET_CR &=
   ~(uint32_t)(SOFT_RESET_CR_I2C0_MASK | SOFT_RESET_CR_I2C1_MASK);
```

... on the E51 (HSS) then it works, but if you do it on U54_1 it doesn't?

**Comment by eenurkka** [comment]
@griffini , exactly. On E51 it works, but not on U54_1. I can clear the bits on U54_1, but then I2C doesn't really work. I mean I can clear the bits on U54_1 and read them back to confirm they're unset, but I2C register writes go nowhere (reading back say only 0's no matter what I write).

**Comment by griffini** [comment]
Hmmm... there is nothing strange or special in the architecture for accessing the MSS peripherals from the E51 vs the U54s.

Our Linux I2C driver (which is in the process of being upstreamed) successfully works the same way as you describe - it enables the clock and brings the I2C device out of reset on a U54... so this strategy does work.

What are you running on the other U54s? Could one of them possibly be interfering with your attempts to bring the I2C up on U54_1 ?

**Comment by eenurkka** [comment]
@griffini , and you all, thanks for your quick and great support, appreciated! I have nothing running on the other cores. I have the i2c working reliably now, so this issue with only E51 bringing the i2c out of reset must be my mistake, nothing to worry about.

**Comment by griffini** [comment]
Fantastic news, I'm happy it is now working for you!
