### ISSUE TITLE
Plan to upgrade OpenSBI?

### ISSUE THREAD

**Issue by lbmeng** [polarfire-soc/hart-software-services#27]
Current version of HSS is still using OpenSBI v0.6 which is quite old.

Is there any plan to upgrade to a recent version of OpenSBI that supports HSM, etc?

**Comment by griffini** [comment]
Yes, the next release of the HSS (being tested at the moment) does include a recent OpenSBI that supports HSM.

**Comment by Cyril-Jean** [comment]
@lbmeng Release 2021.08 includes the openSBI update.
