### ISSUE TITLE
Incorrect reference to "2021.04 Icicle Kit Reference Design" in the HSS v2021.08 release notes?

### ISSUE THREAD

**Issue by kevinscully100** [polarfire-soc/hart-software-services#28]
@Cyril-Jean [HSS v2021.08 release notes](https://github.com/polarfire-soc/hart-software-services/releases/tag/2021.08): "Icicle Kit Reference Design Programming File" section: 
should "2021.04 Icicle Kit Reference Design" be "2021.08 Icicle Kit Reference Design"?

**Comment by Cyril-Jean** [comment]
Well spotted. Corrected.
