### ISSUE TITLE
HSS fails to boot on MPFS250T_ES FCSG536

### ISSUE THREAD

**Issue by fcuzzocrea** [polarfire-soc/hart-software-services#41]
Ciao!

This is just to report that, current version of HSS fails to boot on MPFS250T_ES die FCSG536 package. The issue seems to be somewhere into the HAL code.

From my tests, something in the mss_nwc_init() causes the CPU to reset. To get it working, I had to update the mpfs_hal to the latest version available from the platform repo.

Do you plan to update BsP version shipped with HSS ? Thanks

**Comment by Cyril-Jean** [comment]
Interesting. Could you try with the current master of the HSS?
Which type of DDR are you using? LPDDR4 or other?

**Comment by fcuzzocrea** [comment]
No, simply DDR4. I can give a shot to the current master later and let you know!

**Comment by fcuzzocrea** [comment]
I just had a try - current master of HSS boots fine

**Comment by griffini** [comment]
> I just had a try - current master of HSS boots fine

@fcuzzocrea , delighted to hear this. I'll close this issue now.
